version: '3'

services:
  keycloak_db:
      container_name: keycloak_db
      image: postgres:16
      volumes:
        - ${KC_STORAGE_POSTGRES:-keycloak-/srv/docker_keycloak/data/postgres}:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: ${POSTGRES_USER:-keycloak}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-eX4mP13p455w0Rd}
      ports:
        - "5432:5432"

  keycloak:
      # build: .
      container_name: keycloak
      image: quay.io/keycloak/keycloak:24.0.1
      environment:
        # https://www.keycloak.org/server/configuration
        # https://www.keycloak.org/server/all-config
        KC_LOG_LEVEL: debug
        KC_DB: postgres
        KC_DB_URL_HOST: keycloak_db
        KC_DB_URL_PORT: 5432
        KC_DB_URL_DATABASE: keycloak
        KC_HTTP_ENABLED: true
        #KC_DB_URL: 'jdbc:postgresql://postgres_db/keycloak'
        KC_DB_USERNAME: ${POSTGRES_USER:-keycloak}
        KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-eX4mP13p455w0Rd}
        KC_DB_SCHEMA: public
        #KC_HOSTNAME_URL: "http://${KC_HOSTNAME:-your.tld.com}:8080"
        #KC_HOSTNAME_ADMIN_URL: "http://${KC_HOSTNAME}:8080"
        KC_HTTP_PORT: 8080
        KC_HOSTNAME_STRICT_HTTPS: false
        KC_HOSTNAME_STRICT: false
        KC_PROXY: edge
        HTTP_ADDRESS_FORWARDING: true
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-eX4mP13p455w0Rd}
      # command: start --optimizeda
      links:
        - keycloak_db:postgres
      networks:
        - app_network
      depends_on:
        - keycloak_db
      entrypoint: /opt/keycloak/bin/kc.sh start --proxy edge --hostname-strict=false

networks:
  - app_network:
      name: ${DOCKER_APP_NETWORK}
      external: true
    
