version: '3.8'

services:
  nginx:
    restart: always
    image: nginx:latest
    networks:
      - app_network
    ports:
      - 443:443
      - 80:80
      - 8181:8181
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d/:ro
      - ${NGINX_CERTBOT_DIR}:/var/www/certbot/:ro
      - ${NGINX_LETSENCR_DIR}:/etc/letsencrypt/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ${NGINX_CERTBOT_DIR}:/var/www/certbot/
      - ${NGINX_LETSENCR_DIR}:/etc/letsencrypt/
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}
    depends_on:
      - nginx
  keycloakdb:
      container_name: keycloakdb
      image: postgres:16
      volumes:
        - ${KC_STORAGE_POSTGRES:-keycloak-/srv/docker_keycloak/data/postgres}:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: ${POSTGRES_USER:-keycloak}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-eX4mP13p455w0Rd}
      networks:
        - app_network
      ports:
        - "5432:5432"
  keycloak:
      # build: .
      container_name: keycloak
      image: quay.io/keycloak/keycloak:24.0.1
      environment:
        # https://www.keycloak.org/server/configuration
        # https://www.keycloak.org/server/all-config
        KC_LOG_LEVEL: debug
        KC_DB: postgres
        KC_DB_URL_HOST: keycloakdb
        KC_DB_URL_PORT: 5432
        KC_DB_URL_DATABASE: keycloak
        KC_HTTP_ENABLED: true
        #KC_DB_URL: 'jdbc:postgresql://postgres_db/keycloak'
        KC_DB_USERNAME: ${POSTGRES_USER:-keycloak}
        KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-eX4mP13p455w0Rd}
        KC_DB_SCHEMA: public
        #KC_HOSTNAME_URL: "http://${KC_HOSTNAME:-your.tld.com}:8080"
        #KC_HOSTNAME_ADMIN_URL: "http://${KC_HOSTNAME}:8080"
        KC_HTTP_PORT: 8080
        KC_HOSTNAME_STRICT_HTTPS: false
        KC_HOSTNAME_STRICT: false
        KC_PROXY: edge
        HTTP_ADDRESS_FORWARDING: true
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-eX4mP13p455w0Rd}
      # command: start --optimizeda
      networks:
        - app_network
      entrypoint: /opt/keycloak/bin/kc.sh start --proxy edge --hostname-strict=false --verbose

networks:
  app_network:
    name: ${DOCKER_APP_NETWORK}
    external: true
